app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://phobos.butterflycluster.com:443

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: https://phobos.butterflycluster.com:443
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  cors:
    origin: 'https://phobos.butterflycluster.com'
    methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
    credentials: true
    allowedHeaders: [ 'Authorization', 'Content-Type', 'X-Requested-With', 'Origin', 'Accept', 'Client-Security-Token', 'Accept-Encoding', 'Accept-Language', 'Host', 'Referer', 'User-Agent' ]

  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

#catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
 # locations: []
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
    - type: url
      target: https://github.com/kingfadzi/homelab/blob/main/catalog-infos/all.yaml

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/docs-template-cookiecutter/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/gitlab-merge-request/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/pull-request/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/rails-demo/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml
      rules:
        - allow: [ Template ]

    - type: url
      target: https://github.com/kingfadzi/software-templates/blob/main/scaffolder-templates/springboot-grpc-template-gl/template.yaml
      rules:
        - allow: [ Template ]
